version: '3'
services:
  omnitron:
    image: ghcr.io/warp-tech/omnitron
    ports:
      - 2222:2222
      - 8888:8888
      - 33306:33306
    volumes:
      - ./data:/data
    stdin_open: true
    tty: true
