[package]
name = "omnitron-web"
version.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
serde.workspace = true
rust-embed = "8.3"
serde_json.workspace = true
thiserror = "1.0"
